### ISSUE TITLE
[사이드바] 모든 키워드 삭제시 초기화 이슈

### ISSUE THREAD

**Issue by Jincy7** [devSoyoung/whale-extension-keycrab#17]
- 모든 키워드를 삭제한 경우에 초기화면이 정상적으로 나타나지 않고있습니다!
![image](https://user-images.githubusercontent.com/37904207/68471009-9b123880-0260-11ea-86e3-d60a6944932b.png)

![image](https://user-images.githubusercontent.com/37904207/68471036-ab2a1800-0260-11ea-903a-4b57ca7503a5.png)

**Comment by KKonzi** [comment]
244340c07f502845c375b412858b275ec3d815f5 수정하였습니당 :D
